### PR TITLE
help us find page integrated with backend

### PR DESCRIPTION
**Pull request by ThapaVinay**

### CODE REVIEW

**Comment by ThapaVinay** [comment]
#93

**Comment by ThapaVinay** [comment]
should i create a new pr? i have committed the changes if you want to merge this one

**Comment by aakshitaa** [comment]
No need to creat new pr, just commit all the changes in this one

**Comment by ThapaVinay** [comment]
done committed everything i have

**Review by aakshitaa — APPROVED** [review]
Approved!

**Pull request merged**
