### PR TITLE
Added navbar with updates

### PR DESCRIPTION
**Pull request by helloakash1701**
I removed the bootstrap because of it my navbar was getting changed for some reason. This is the pr for "Create a Navbar #1"

Working Nav

image

### CODE REVIEW

**Review by aakshitaa — CHANGES_REQUESTED** [review]
It isn't advisable to remove bootstrap because others might want to use it while making some pages, so work on the navbar such that it works as normal even after adding bootstrap. It's basically related to css, else there will be issues regarding this in future. Also please don't put readme and workflow in lost and found folder, let it be where it was. So your overall changes are:

- [ ] Make changes so that works fine without removing bootstrap.

- [ ] Don't move readme and workflow.md

- [ ]

**Comment by helloakash1701** [comment]
Okay I'll work on that

**Comment by ThapaVinay** [comment]
@helloakash1701  just don't use classname = {container, row} that you have used in your project. rename it to something else . this should resolve the bootstrap conflict

**Comment by helloakash1701** [comment]
Okay ill look into it thanks 🙌

**Review by aakshitaa — APPROVED** [review]
Approved 👍

**Pull request closed without merging**
