### PR TITLE
Improved the Readme.

### PR DESCRIPTION
**Pull request by AnkitAnandMastery17**
Hey @aakshitaa , I can't add the images because I am not from Upes. I have improved as far as possible. Kindly give feedback and find all right to merge it.

### CODE REVIEW

**Comment by AnkitAnandMastery17** [comment]
This is the Issue #130

**Comment by aakshitaa** [comment]
> Hey @aakshitaa , I can't add the images because I am not from Upes. I have improved as far as possible. Kindly give feedback and find all right to merge it.

Hello @AnkitAnandMastery17 I will share the images of the protected pages in a while, then you may add them and create new pr, give me 30 min

**Comment by AnkitAnandMastery17** [comment]
Ok.

**Comment by AnkitAnandMastery17** [comment]
Also, tell me which sections to add.

**Pull request closed without merging**
